"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"
import { toast } from "@/hooks/use-toast"

// Define available languages
export type Language =
  | "en"
  | "uk"
  | "de"
  | "es"
  | "fr"
  | "it"
  | "zh-CN"
  | "zh-TW"
  | "ja"
  | "ko"
  | "pt-BR"
  | "ar"
  | "pl"
  | "tr"
  | "hi"
  | "nl"
  | "vi"
  | "ru"
  | "sv"
  | "no"
  | "fi"
  | "da"
  | "cs"
  | "hu"
  | "ro"
  | "bg"
  | "el"
  | "th"

// Define translations interface
interface Translations {
  [key: string]: {
    [key: string]: string
  }
}

// Create translations object (abbreviated for brevity)
const translations: Translations = {
  // Basic translations included here
  settings: {
    en: "Settings",
    uk: "Налаштування",
    ru: "Настройки",
    de: "Einstellungen",
    fr: "Paramètres",
    // ... other languages
  },
  language: {
    en: "Language",
    uk: "Мова",
    ru: "Язык",
    de: "Sprache",
    fr: "Langue",
    // ... other languages
  },
  // ... other translation keys
  settings: {
    en: "Settings",
    uk: "Налаштування",
    de: "Einstellungen",
    es: "Configuración",
    fr: "Paramètres",
    it: "Impostazioni",
    "zh-CN": "设置",
    "zh-TW": "設置",
    ja: "設定",
    ko: "설정",
    "pt-BR": "Configurações",
    ar: "الإعدادات",
    pl: "Ustawienia",
    tr: "Ayarlar",
    hi: "सेटिंग्स",
    nl: "Instellingen",
    vi: "Cài đặt",
    ru: "Настройки",
    sv: "Inställningar",
    no: "Innstillinger",
    fi: "Asetukset",
    da: "Indstillinger",
    cs: "Nastavení",
    hu: "Beállítások",
    ro: "Setări",
    bg: "Настройки",
    el: "Ρυθμίσεις",
    th: "การตั้งค่า",
  },
  account: {
    en: "Account",
    uk: "Обліковий запис",
    de: "Konto",
    es: "Cuenta",
    fr: "Compte",
    it: "Account",
    "zh-CN": "账户",
    "zh-TW": "帳戶",
    ja: "アカウント",
    ko: "계정",
    "pt-BR": "Conta",
    ar: "الحساب",
    pl: "Konto",
    tr: "Hesap",
    hi: "खाता",
    nl: "Account",
    vi: "Tài khoản",
    ru: "Аккаунт",
    sv: "Konto",
    no: "Konto",
    fi: "Tili",
    da: "Konto",
    cs: "Účet",
    hu: "Fiók",
    ro: "Cont",
    bg: "Акаунт",
    el: "Λογαριασμός",
    th: "บัญชี",
  },
  preferences: {
    en: "Preferences",
    uk: "Налаштування",
    de: "Präferenzen",
    es: "Preferencias",
    fr: "Préférences",
    it: "Preferenze",
    "zh-CN": "首选项",
    "zh-TW": "偏好設定",
    ja: "設定",
    ko: "환경설정",
    "pt-BR": "Preferências",
    ar: "التفضيلات",
    pl: "Preferencje",
    tr: "Tercihler",
    hi: "प्राथमिकताएँ",
    nl: "Voorkeuren",
    vi: "Tùy chọn",
    ru: "Предпочтения",
    sv: "Inställningar",
    no: "Preferanser",
    fi: "Asetukset",
    da: "Præferencer",
    cs: "Předvolby",
    hu: "Beállítások",
    ro: "Preferințe",
    bg: "Предпочитания",
    el: "Προτιμήσεις",
    th: "การตั้งค่า",
  },
  notifications: {
    en: "Notifications",
    uk: "Сповіщення",
    de: "Benachrichtigungen",
    es: "Notificaciones",
    fr: "Notifications",
    it: "Notifiche",
    "zh-CN": "通知",
    "zh-TW": "通知",
    ja: "通知",
    ko: "알림",
    "pt-BR": "Notificações",
    ar: "الإشعارات",
    pl: "Powiadomienia",
    tr: "Bildirimler",
    hi: "सूचनाएँ",
    nl: "Meldingen",
    vi: "Thông báo",
    ru: "Уведомления",
    sv: "Aviseringar",
    no: "Varsler",
    fi: "Ilmoitukset",
    da: "Notifikationer",
    cs: "Oznámení",
    hu: "Értesítések",
    ro: "Notificări",
    bg: "Известия",
    el: "Ειδοποιήσεις",
    th: "การแจ้งเตือน",
  },
  general: {
    en: "General",
    uk: "Загальні",
    de: "Allgemein",
    es: "General",
    fr: "Général",
    it: "Generale",
    "zh-CN": "通用",
    "zh-TW": "一般",
    ja: "一般",
    ko: "일반",
    "pt-BR": "Geral",
    ar: "عام",
    pl: "Ogólne",
    tr: "Genel",
    hi: "सामान्य",
    nl: "Algemeen",
    vi: "Chung",
    ru: "Общие",
    sv: "Allmänt",
    no: "Generelt",
    fi: "Yleiset",
    da: "Generelt",
    cs: "Obecné",
    hu: "Általános",
    ro: "General",
    bg: "Общи",
    el: "Γενικά",
    th: "ทั่วไป",
  },
  language: {
    en: "Language",
    uk: "Мова",
    de: "Sprache",
    es: "Idioma",
    fr: "Langue",
    it: "Lingua",
    "zh-CN": "语言",
    "zh-TW": "語言",
    ja: "言語",
    ko: "언어",
    "pt-BR": "Idioma",
    ar: "اللغة",
    pl: "Język",
    tr: "Dil",
    hi: "भाषा",
    nl: "Taal",
    vi: "Ngôn ngữ",
    ru: "Язык",
    sv: "Språk",
    no: "Språk",
    fi: "Kieli",
    da: "Sprog",
    cs: "Jazyk",
    hu: "Nyelv",
    ro: "Limbă",
    bg: "Език",
    el: "Γλώσσα",
    th: "ภาษา",
  },
  english: {
    en: "English",
    uk: "Англійська",
    de: "Englisch",
    es: "Inglés",
    fr: "Anglais",
    it: "Inglese",
    "zh-CN": "英语",
    "zh-TW": "英語",
    ja: "英語",
    ko: "영어",
    "pt-BR": "Inglês",
    ar: "الإنجليزية",
    pl: "Angielski",
    tr: "İngilizce",
    hi: "अंग्रेज़ी",
    nl: "Engels",
    vi: "Tiếng Anh",
    ru: "Английский",
    sv: "Engelska",
    no: "Engelsk",
    fi: "Englanti",
    da: "Engelsk",
    cs: "Angličtina",
    hu: "Angol",
    ro: "Engleză",
    bg: "Английски",
    el: "Αγγλικά",
    th: "อังกฤษ",
  },
  ukrainian: {
    en: "Ukrainian",
    uk: "Українська",
    de: "Ukrainisch",
    es: "Ucraniano",
    fr: "Ukrainien",
    it: "Ucraino",
    "zh-CN": "乌克兰语",
    "zh-TW": "烏克蘭語",
    ja: "ウクライナ語",
    ko: "우크라이나어",
    "pt-BR": "Ucraniano",
    ar: "الأوكرانية",
    pl: "Ukraiński",
    tr: "Ukraynaca",
    hi: "यूक्रेनी",
    nl: "Oekraïens",
    vi: "Tiếng Ukraine",
    ru: "Украинский",
    sv: "Ukrainska",
    no: "Ukrainsk",
    fi: "Ukraina",
    da: "Ukrainsk",
    cs: "Ukrajinština",
    hu: "Ukrán",
    ro: "Ucraineană",
    bg: "Украински",
    el: "Ουκρανικά",
    th: "ยูเครน",
  },
  german: {
    en: "German",
    uk: "Німецька",
    de: "Deutsch",
    es: "Alemán",
    fr: "Allemand",
    it: "Tedesco",
    "zh-CN": "德语",
    "zh-TW": "德語",
    ja: "ドイツ語",
    ko: "독일어",
    "pt-BR": "Alemão",
    ar: "الألمانية",
    pl: "Niemiecki",
    tr: "Almanca",
    hi: "जर्मन",
    nl: "Duits",
    vi: "Tiếng Đức",
    ru: "Немецкий",
    sv: "Tyska",
    no: "Tysk",
    fi: "Saksa",
    da: "Tysk",
    cs: "Němčina",
    hu: "Német",
    ro: "Germană",
    bg: "Немски",
    el: "Γερμανικά",
    th: "เยอรมัน",
  },
  spanish: {
    en: "Spanish",
    uk: "Іспанська",
    de: "Spanisch",
    es: "Español",
    fr: "Français",
    it: "Spagnolo",
    "zh-CN": "西班牙语",
    "zh-TW": "西班牙語",
    ja: "スペイン語",
    ko: "스페인어",
    "pt-BR": "Espanhol",
    ar: "الإسبانية",
    pl: "Hiszpański",
    tr: "İspanyolca",
    hi: "स्पेनिश",
    nl: "Spaans",
    vi: "Tiếng Tây Ban Nha",
    ru: "Испанский",
    sv: "Spanska",
    no: "Spansk",
    fi: "Espanja",
    da: "Spansk",
    cs: "Španělština",
    hu: "Spanyol",
    ro: "Spaniolă",
    bg: "Испански",
    el: "Ισπανικά",
    th: "สเปน",
  },
  french: {
    en: "French",
    uk: "Французька",
    de: "Französisch",
    es: "Francés",
    fr: "Français",
    it: "Francese",
    "zh-CN": "法语",
    "zh-TW": "法語",
    ja: "フランス語",
    ko: "프랑스어",
    "pt-BR": "Francês",
    ar: "الفرنسية",
    pl: "Francuski",
    tr: "Fransızca",
    hi: "फ्रेंच",
    nl: "Frans",
    vi: "Tiếng Pháp",
    ru: "Французский",
    sv: "Franska",
    no: "Fransk",
    fi: "Ranska",
    da: "Fransk",
    cs: "Francouzština",
    hu: "Francia",
    ro: "Franceză",
    bg: "Френски",
    el: "Γαλλικά",
    th: "ฝรั่งเศส",
  },
  italian: {
    en: "Italian",
    uk: "Італійська",
    de: "Italienisch",
    es: "Italiano",
    fr: "Italien",
    it: "Italiano",
    "zh-CN": "意大利语",
    "zh-TW": "義大利語",
    ja: "イタリア語",
    ko: "이탈리아어",
    "pt-BR": "Italiano",
    ar: "الإيطالية",
    pl: "Włoski",
    tr: "İtalyanca",
    hi: "इतालवी",
    nl: "Italiaans",
    vi: "Tiếng Ý",
    ru: "Итальянский",
    sv: "Italienska",
    no: "Italiensk",
    fi: "Italia",
    da: "Italiensk",
    cs: "Italština",
    hu: "Olasz",
    ro: "Italiană",
    bg: "Италиански",
    el: "Ιταλικά",
    th: "อิตาลี",
  },
  chineseSimplified: {
    en: "Chinese (Simplified)",
    uk: "Китайська (спрощена)",
    de: "Chinesisch (Vereinfacht)",
    es: "Chino (Simplificado)",
    fr: "Chinois (Simplifié)",
    it: "Cinese (Semplificato)",
    "zh-CN": "简体中文",
    "zh-TW": "簡體中文",
    ja: "中国語 (簡体字)",
    ko: "중국어 (간체)",
    "pt-BR": "Chinês (Simplificado)",
    ar: "الصينية (المبسطة)",
    pl: "Chiński (Uproszczony)",
    tr: "Çince (Basitleştirilmiş)",
    hi: "चीनी (सरलीकृत)",
    nl: "Chinees (Vereenvoudigd)",
    vi: "Tiếng Trung (Giản thể)",
    ru: "Китайский (упрощенный)",
    sv: "Kinesiska (förenklad)",
    no: "Kinesisk (forenklet)",
    fi: "Kiina (yksinkertaistettu)",
    da: "Kinesisk (forenklet)",
    cs: "Čínština (zjednodušená)",
    hu: "Kínai (egyszerűsített)",
    ro: "Chineză (simplificată)",
    bg: "Китайски (опростен)",
    el: "Κινέζικα (Απλοποιημένα)",
    th: "จีน (ตัวย่อ)",
  },
  chineseTraditional: {
    en: "Chinese (Traditional)",
    uk: "Китайська (традиційна)",
    de: "Chinesisch (Traditionell)",
    es: "Chino (Tradicional)",
    fr: "Chinois (Traditionnel)",
    it: "Cinese (Tradizionale)",
    "zh-CN": "繁体中文",
    "zh-TW": "繁體中文",
    ja: "中国語 (繁体字)",
    ko: "중국어 (번체)",
    "pt-BR": "Chinês (Tradicional)",
    ar: "الصينية (التقليدية)",
    pl: "Chiński (Tradycyjny)",
    tr: "Çince (Geleneksel)",
    hi: "चीनी (पारंपरिक)",
    nl: "Chinees (Traditioneel)",
    vi: "Tiếng Trung (Phồn thể)",
    ru: "Китайский (традиционный)",
    sv: "Kinesiska (traditionell)",
    no: "Kinesisk (tradisjonell)",
    fi: "Kiina (perinteinen)",
    da: "Kinesisk (traditionel)",
    cs: "Čínština (tradiční)",
    hu: "Kínai (hagyományos)",
    ro: "Chineză (tradițională)",
    bg: "Китайски (традиционен)",
    el: "Κινέζικα (Παραδοσιακά)",
    th: "จีน (ตัวเต็ม)",
  },
  japanese: {
    en: "Japanese",
    uk: "Японська",
    de: "Japanisch",
    es: "Japonés",
    fr: "Japonais",
    it: "Giapponese",
    "zh-CN": "日语",
    "zh-TW": "日語",
    ja: "日本語",
    ko: "일본어",
    "pt-BR": "Japonês",
    ar: "اليابانية",
    pl: "Japoński",
    tr: "Japonca",
    hi: "जापानी",
    nl: "Japans",
    vi: "Tiếng Nhật",
    ru: "Японский",
    sv: "Japanska",
    no: "Japansk",
    fi: "Japani",
    da: "Japansk",
    cs: "Japonština",
    hu: "Japán",
    ro: "Japoneză",
    bg: "Японски",
    el: "Ιαπωνικά",
    th: "ญี่ปุ่น",
  },
  korean: {
    en: "Korean",
    uk: "Корейська",
    de: "Koreanisch",
    es: "Coreano",
    fr: "Coréen",
    it: "Coreano",
    "zh-CN": "韩语",
    "zh-TW": "韓語",
    ja: "韓国語",
    ko: "한국어",
    "pt-BR": "Coreano",
    ar: "الكورية",
    pl: "Koreański",
    tr: "Korece",
    hi: "कोरियाई",
    nl: "Koreaans",
    vi: "Tiếng Hàn",
    ru: "Корейский",
    sv: "Koreanska",
    no: "Koreansk",
    fi: "Korea",
    da: "Koreansk",
    cs: "Korejština",
    hu: "Koreai",
    ro: "Coreeană",
    bg: "Корейски",
    el: "Κορεατικά",
    th: "เกาหลี",
  },
  portugueseBrazil: {
    en: "Portuguese (Brazil)",
    uk: "Португальська (Бразилія)",
    de: "Portugiesisch (Brasilien)",
    es: "Portugués (Brasil)",
    fr: "Portugais (Brésil)",
    it: "Portoghese (Brasile)",
    "zh-CN": "葡萄牙语（巴西）",
    "zh-TW": "葡萄牙語（巴西）",
    ja: "ポルトガル語（ブラジル）",
    ko: "포르투갈어 (브라질)",
    "pt-BR": "Português (Brasil)",
    ar: "البرتغالية (البرازيل)",
    pl: "Portugalski (Brazylia)",
    tr: "Portekizce (Brezilya)",
    hi: "पुर्तगाली (ब्राज़ील)",
    nl: "Portugees (Brazilië)",
    vi: "Tiếng Bồ Đào Nha (Brazil)",
    ru: "Португальский (Бразилия)",
    sv: "Portugisiska (Brasilien)",
    no: "Portugisisk (Brasil)",
    fi: "Portugali (Brasilia)",
    da: "Portugisisk (Brasilien)",
    cs: "Portugalština (Brazílie)",
    hu: "Portugál (Brazília)",
    ro: "Portugheză (Brazilia)",
    bg: "Португалски (Бразилия)",
    el: "Πορτογαλικά (Βραζιλία)",
    th: "โปรตุเกส (บราซิล)",
  },
  arabic: {
    en: "Arabic",
    uk: "Арабська",
    de: "Arabisch",
    es: "Árabe",
    fr: "Arabe",
    it: "Arabo",
    "zh-CN": "阿拉伯语",
    "zh-TW": "阿拉伯語",
    ja: "アラビア語",
    ko: "아랍어",
    "pt-BR": "Árabe",
    ar: "العربية",
    pl: "Arabski",
    tr: "Arapça",
    hi: "अरबी",
    nl: "Arabisch",
    vi: "Tiếng Ả Rập",
    ru: "Арабский",
    sv: "Arabiska",
    no: "Arabisk",
    fi: "Arabia",
    da: "Arabisk",
    cs: "Arabština",
    hu: "Arab",
    ro: "Arabă",
    bg: "Арабски",
    el: "Αραβικά",
    th: "อาหรับ",
  },
  polish: {
    en: "Polish",
    uk: "Польська",
    de: "Polnisch",
    es: "Polaco",
    fr: "Polonais",
    it: "Polacco",
    "zh-CN": "波兰语",
    "zh-TW": "波蘭語",
    ja: "ポーランド語",
    ko: "폴란드어",
    "pt-BR": "Polonês",
    ar: "البولندية",
    pl: "Polski",
    tr: "Lehçe",
    hi: "पोलिश",
    nl: "Pools",
    vi: "Tiếng Ba Lan",
    ru: "Польский",
    sv: "Polska",
    no: "Polsk",
    fi: "Puola",
    da: "Polsk",
    cs: "Polština",
    hu: "Lengyel",
    ro: "Poloneză",
    bg: "Полски",
    el: "Πολωνικά",
    th: "โปแลนด์",
  },
  turkish: {
    en: "Turkish",
    uk: "Турецька",
    de: "Türkisch",
    es: "Turco",
    fr: "Turc",
    it: "Turco",
    "zh-CN": "土耳其语",
    "zh-TW": "土耳其語",
    ja: "トルコ語",
    ko: "터키어",
    "pt-BR": "Turco",
    ar: "التركية",
    pl: "Turecki",
    tr: "Türkçe",
    hi: "तुर्की",
    nl: "Turks",
    vi: "Tiếng Thổ Nhĩ Kỳ",
    ru: "Турецкий",
    sv: "Turkiska",
    no: "Tyrkisk",
    fi: "Turkki",
    da: "Tyrkisk",
    cs: "Turečtina",
    hu: "Török",
    ro: "Turcă",
    bg: "Турски",
    el: "Τουρκικά",
    th: "ตุรกี",
  },
  hindi: {
    en: "Hindi",
    uk: "Хінді",
    de: "Hindi",
    es: "Hindi",
    fr: "Hindi",
    it: "Hindi",
    "zh-CN": "印地语",
    "zh-TW": "印地語",
    ja: "ヒンディー語",
    ko: "힌디어",
    "pt-BR": "Hindi",
    ar: "الهندية",
    pl: "Hindi",
    tr: "Hintçe",
    hi: "हिन्दी",
    nl: "Hindi",
    vi: "Tiếng Hindi",
    ru: "Хинди",
    sv: "Hindi",
    no: "Hindi",
    fi: "Hindi",
    da: "Hindi",
    cs: "Hindština",
    hu: "Hindi",
    ro: "Hindi",
    bg: "Хинди",
    el: "Χίντι",
    th: "ฮินดี",
  },
  dutch: {
    en: "Dutch",
    uk: "Нідерландська",
    de: "Niederländisch",
    es: "Holandés",
    fr: "Néerlandais",
    it: "Olandese",
    "zh-CN": "荷兰语",
    "zh-TW": "荷蘭語",
    ja: "オランダ語",
    ko: "네덜란드어",
    "pt-BR": "Holandês",
    ar: "الهولندية",
    pl: "Holenderski",
    tr: "Hollandaca",
    hi: "डच",
    nl: "Nederlands",
    vi: "Tiếng Hà Lan",
    ru: "Нидерландский",
    sv: "Nederländska",
    no: "Nederlandsk",
    fi: "Hollanti",
    da: "Hollandsk",
    cs: "Nizozemština",
    hu: "Holland",
    ro: "Olandeză",
    bg: "Холандски",
    el: "Ολλανδικά",
    th: "ดัตช์",
  },
  vietnamese: {
    en: "Vietnamese",
    uk: "В'єтнамська",
    de: "Vietnamesisch",
    es: "Vietnamita",
    fr: "Vietnamien",
    it: "Vietnamita",
    "zh-CN": "越南语",
    "zh-TW": "越南語",
    ja: "ベトナム語",
    ko: "베트남어",
    "pt-BR": "Vietnamita",
    ar: "الفيتنامية",
    pl: "Wietnamski",
    tr: "Vietnamca",
    hi: "वियतनामी",
    nl: "Vietnamees",
    vi: "Tiếng Việt",
    ru: "Вьетнамский",
    sv: "Vietnamesiska",
    no: "Vietnamesisk",
    fi: "Vietnam",
    da: "Vietnamesisk",
    cs: "Vietnamština",
    hu: "Vietnámi",
    ro: "Vietnameză",
    bg: "Виетнамски",
    el: "Βιετναμέζικα",
    th: "เวียดนาม",
  },
  russian: {
    en: "Russian",
    uk: "Російська",
    de: "Russisch",
    es: "Ruso",
    fr: "Russe",
    it: "Russo",
    "zh-CN": "俄语",
    "zh-TW": "俄語",
    ja: "ロシア語",
    ko: "러시아어",
    "pt-BR": "Russo",
    ar: "الروسية",
    pl: "Rosyjski",
    tr: "Rusça",
    hi: "रूसी",
    nl: "Russisch",
    vi: "Tiếng Nga",
    ru: "Русский",
    sv: "Ryska",
    no: "Russisk",
    fi: "Venäjä",
    da: "Russisk",
    cs: "Ruština",
    hu: "Orosz",
    ro: "Rusă",
    bg: "Руски",
    el: "Ρωσικά",
    th: "รัสเซีย",
  },
  swedish: {
    en: "Swedish",
    uk: "Шведська",
    de: "Schwedisch",
    es: "Sueco",
    fr: "Suédois",
    it: "Svedese",
    "zh-CN": "瑞典语",
    "zh-TW": "瑞典語",
    ja: "スウェーデン語",
    ko: "스웨덴어",
    "pt-BR": "Sueco",
    ar: "السويدية",
    pl: "Szwedzki",
    tr: "İsveççe",
    hi: "स्वीडिश",
    nl: "Zweeds",
    vi: "Tiếng Thụy Điển",
    ru: "Шведский",
    sv: "Svenska",
    no: "Norsk",
    fi: "Ruotsi",
    da: "Svensk",
    cs: "Švédština",
    hu: "Svéd",
    ro: "Suedeză",
    bg: "Шведски",
    el: "Σουηδικά",
    th: "สวีเดน",
  },
  // Add more translations for all supported languages
  saveChanges: {
    en: "Save Changes",
    uk: "Зберегти зміни",
    de: "Änderungen speichern",
    es: "Guardar cambios",
    fr: "Enregistrer les modifications",
    it: "Salva modifiche",
    "zh-CN": "保存更改",
    "zh-TW": "儲存變更",
    ja: "変更を保存",
    ko: "변경 사항 저장",
    "pt-BR": "Salvar alterações",
    ar: "حفظ التغييرات",
    pl: "Zapisz zmiany",
    tr: "Değişiklikleri Kaydet",
    hi: "परिवर्तन सहेजें",
    nl: "Wijzigingen opslaan",
    vi: "Lưu thay đổi",
    ru: "Сохранить изменения",
    sv: "Spara ändringar",
    no: "Lagre endringer",
    fi: "Tallenna muutokset",
    da: "Gem ændringer",
    cs: "Uložit změny",
    hu: "Változtatások mentése",
    ro: "Salvează modificările",
    bg: "Запази промените",
    el: "Αποθήκευση αλλαγών",
    th: "บันทึกการเปลี่ยนแปลง",
  },
  profile: {
    en: "Profile",
    uk: "Профіль",
    de: "Profil",
    es: "Perfil",
    fr: "Profil",
    it: "Profilo",
    "zh-CN": "个人资料",
    "zh-TW": "個人資料",
    ja: "プロフィール",
    ko: "프로필",
    "pt-BR": "Perfil",
    ar: "الملف الشخصي",
    pl: "Profil",
    tr: "Profil",
    hi: "प्रोफ़ाइल",
    nl: "Profiel",
    vi: "Hồ sơ",
    ru: "Профиль",
    sv: "Profil",
    no: "Profil",
    fi: "Profiili",
    da: "Profil",
    cs: "Profil",
    hu: "Profil",
    ro: "Profil",
    bg: "Профил",
    el: "Προφίλ",
    th: "โปรไฟล์",
  },
  editProfile: {
    en: "Edit Profile",
    uk: "Редагувати профіль",
    de: "Profil bearbeiten",
    es: "Editar perfil",
    fr: "Modifier le profil",
    it: "Modifica profilo",
    "zh-CN": "编辑个人资料",
    "zh-TW": "編輯個人資料",
    ja: "プロフィールを編集",
    ko: "프로필 편집",
    "pt-BR": "Editar perfil",
    ar: "تعديل الملف الشخصي",
    pl: "Edytuj profil",
    tr: "Profili Düzenle",
    hi: "प्रोफ़ाइल संपादित करें",
    nl: "Profiel bewerken",
    vi: "Chỉnh sửa hồ sơ",
    ru: "Редактировать профиль",
    sv: "Redigera profil",
    no: "Rediger profil",
    fi: "Muokkaa profiilia",
    da: "Rediger profil",
    cs: "Upravit profil",
    hu: "Profil szerkesztése",
    ro: "Editare profil",
    bg: "Редактиране на профил",
    el: "Επεξεργασία προφίλ",
    th: "แก้ไขโปรไฟล์",
  },
  changePassword: {
    en: "Change Password",
    uk: "Змінити пароль",
    de: "Passwort ändern",
    es: "Cambiar contraseña",
    fr: "Changer le mot de passe",
    it: "Cambia password",
    "zh-CN": "更改密码",
    "zh-TW": "變更密碼",
    ja: "パスワードを変更",
    ko: "비밀번호 변경",
    "pt-BR": "Alterar senha",
    ar: "تغيير كلمة المرور",
    pl: "Zmień hasło",
    tr: "Şifre Değiştir",
    hi: "पासवर्ड बदलें",
    nl: "Wachtwoord wijzigen",
    vi: "Đổi mật khẩu",
    ru: "Изменить пароль",
    sv: "Ändra lösenord",
    no: "Endre passord",
    fi: "Vaihda salasana",
    da: "Skift adgangskode",
    cs: "Změnit heslo",
    hu: "Jelszó módosítása",
    ro: "Schimbă parola",
    bg: "Промяна на парола",
    el: "Αλλαγή κωδικού",
    th: "เปลี่ยนรหัสผ่าน",
  },
  currentPassword: {
    en: "Current Password",
    uk: "Поточний пароль",
    de: "Aktuelles Passwort",
    es: "Contraseña actual",
    fr: "Mot de passe actuel",
    it: "Password attuale",
    "zh-CN": "当前密码",
    "zh-TW": "目前密碼",
    ja: "現在のパスワード",
    ko: "현재 비밀번호",
    "pt-BR": "Senha atual",
    ar: "كلمة المرور الحالية",
    pl: "Obecne hasło",
    tr: "Mevcut Şifre",
    hi: "वर्तमान पासवर्ड",
    nl: "Huidig wachtwoord",
    vi: "Mật khẩu hiện tại",
    ru: "Текущий пароль",
    sv: "Nuvarande lösenord",
    no: "Nåværende passord",
    fi: "Nykyinen salasana",
    da: "Nuværende adgangskode",
    cs: "Aktuální heslo",
    hu: "Jelenlegi jelszó",
    ro: "Parola actuală",
    bg: "Текуща парола",
    el: "Τρέχων κωδικός",
    th: "รหัสผ่านปัจจุบัน",
  },
  newPassword: {
    en: "New Password",
    uk: "Новий пароль",
    de: "Neues Passwort",
    es: "Nueva contraseña",
    fr: "Nouveau mot de passe",
    it: "Nuova password",
    "zh-CN": "新密码",
    "zh-TW": "新密碼",
    ja: "新しいパスワード",
    ko: "새 비밀번호",
    "pt-BR": "Nova senha",
    ar: "كلمة المرور الجديدة",
    pl: "Nowe hasło",
    tr: "Yeni Şifre",
    hi: "नया पासवर्ड",
    nl: "Nieuw wachtwoord",
    vi: "Mật khẩu mới",
    ru: "Новый пароль",
    sv: "Nytt lösenord",
    no: "Nytt passord",
    fi: "Uusi salasana",
    da: "Ny adgangskode",
    cs: "Nové heslo",
    hu: "Új jelszó",
    ro: "Parolă nouă",
    bg: "Нова парола",
    el: "Νέος κωδικός",
    th: "รหัสผ่านใหม่",
  },
  confirmPassword: {
    en: "Confirm Password",
    uk: "Підтвердити пароль",
    de: "Passwort bestätigen",
    es: "Confirmar contraseña",
    fr: "Confirmer le mot de passe",
    it: "Conferma password",
    "zh-CN": "确认密码",
    "zh-TW": "確認密碼",
    ja: "パスワードを確認",
    ko: "비밀번호 확인",
    "pt-BR": "Confirmar senha",
    ar: "تأكيد كلمة المرور",
    pl: "Potwierdź hasło",
    tr: "Şifreyi Onayla",
    hi: "पासवर्ड की पुष्टि करें",
    nl: "Wachtwoord bevestigen",
    vi: "Xác nhận mật khẩu",
    ru: "Подтвердите пароль",
    sv: "Bekräfta lösenord",
    no: "Bekreft passord",
    fi: "Vahvista salasana",
    da: "Bekræft adgangskode",
    cs: "Potvrdit heslo",
    hu: "Jelszó megerősítése",
    ro: "Confirmă parola",
    bg: "Потвърди паролата",
    el: "Επιβεβαίωση κωδικού",
    th: "ยืนยันรหัสผ่าน",
  },
  searchLanguage: {
    en: "Search language",
    uk: "Пошук мови",
    de: "Sprache suchen",
    es: "Buscar idioma",
    fr: "Rechercher une langue",
    it: "Cerca lingua",
    "zh-CN": "搜索语言",
    "zh-TW": "搜尋語言",
    ja: "言語を検索",
    ko: "언어 검색",
    "pt-BR": "Pesquisar idioma",
    ar: "البحث عن لغة",
    pl: "Szukaj języka",
    tr: "Dil ara",
    hi: "भाषा खोजें",
    nl: "Taal zoeken",
    vi: "Tìm kiếm ngôn ngữ",
    ru: "Поиск языка",
    sv: "Sök språk",
    no: "Søk språk",
    fi: "Hae kieltä",
    da: "Søg sprog",
    cs: "Hledat jazyk",
    hu: "Nyelv keresése",
    ro: "Caută limbă",
    bg: "Търсене на език",
    el: "Αναζήτηση γλώσσας",
    th: "ค้นหาภาษา",
  },
  noLanguagesFound: {
    en: "No languages found",
    uk: "Мови не знайдено",
    de: "Keine Sprachen gefunden",
    es: "No se encontraron idiomas",
    fr: "Aucune langue trouvée",
    it: "Nessuna lingua trovata",
    "zh-CN": "未找到语言",
    "zh-TW": "未找到語言",
    ja: "言語が見つかりません",
    ko: "언어를 찾을 수 없습니다",
    "pt-BR": "Nenhum idioma encontrado",
    ar: "لم يتم العثور على لغات",
    pl: "Nie znaleziono języków",
    tr: "Dil bulunamadı",
    hi: "कोई भाषा नहीं मिली",
    nl: "Geen talen gevonden",
    vi: "Không tìm thấy ngôn ngữ",
    ru: "Языки не найдены",
    sv: "Inga språk hittades",
    no: "Ingen språk funnet",
    fi: "Kieliä ei löytynyt",
    da: "Ingen sprog fundet",
    cs: "Žádné jazyky nenalezeny",
    hu: "Nem található nyelv",
    ro: "Nu s-au găsit limbi",
    bg: "Не са намерени езици",
    el: "Δεν βρέθηκαν γλώσσες",
    th: "ไม่พบภาษา",
  },
  // Navigation & Common UI
  home: {
    en: "Home",
    uk: "Головна",
    de: "Startseite",
    es: "Inicio",
    fr: "Accueil",
    it: "Home",
    "zh-CN": "首页",
    "zh-TW": "首頁",
    ja: "ホーム",
    ko: "홈",
    "pt-BR": "Início",
    ar: "الرئيسية",
    pl: "Strona główna",
    tr: "Ana Sayfa",
    hi: "होम",
    nl: "Home",
    vi: "Trang chủ",
    ru: "Главная",
    sv: "Hem",
    no: "Hjem",
    fi: "Koti",
    da: "Hjem",
    cs: "Domů",
    hu: "Kezdőlap",
    ro: "Acasă",
    bg: "Начало",
    el: "Αρχική",
    th: "หน้าแรก",
  },
  search: {
    en: "Search",
    uk: "Пошук",
    de: "Suche",
    es: "Búsqueda",
    fr: "Recherche",
    it: "Ricerca",
    "zh-CN": "搜索",
    "zh-TW": "搜尋",
    ja: "検索",
    ko: "검색",
    "pt-BR": "Pesquisa",
    ar: "بحث",
    pl: "Szukaj",
    tr: "Arama",
    hi: "खोज",
    nl: "Zoeken",
    vi: "Tìm kiếm",
    ru: "Поиск",
    sv: "Sök",
    no: "Søk",
    fi: "Haku",
    da: "Søg",
    cs: "Hledat",
    hu: "Keresés",
    ro: "Căutare",
    bg: "Търсене",
    el: "Αναζήτηση",
    th: "ค้นหา",
  },
  messages: {
    en: "Messages",
    uk: "Повідомлення",
    de: "Nachrichten",
    es: "Mensajes",
    fr: "Messages",
    it: "Messaggi",
    "zh-CN": "消息",
    "zh-TW": "訊息",
    ja: "メッセージ",
    ko: "메시지",
    "pt-BR": "Mensagens",
    ar: "الرسائل",
    pl: "Wiadomości",
    tr: "Mesajlar",
    hi: "संदेश",
    nl: "Berichten",
    vi: "Tin nhắn",
    ru: "Сообщения",
    sv: "Meddelanden",
    no: "Meldinger",
    fi: "Viestit",
    da: "Beskeder",
    cs: "Zprávy",
    hu: "Üzenetek",
    ro: "Mesaje",
    bg: "Съобщения",
    el: "Μηνύματα",
    th: "ข้อความ",
  },
  bookings: {
    en: "Bookings",
    uk: "Бронювання",
    de: "Buchungen",
    es: "Reservas",
    fr: "Réservations",
    it: "Prenotazioni",
    "zh-CN": "预订",
    "zh-TW": "預訂",
    ja: "予約",
    ko: "예약",
    "pt-BR": "Reservas",
    ar: "الحجوزات",
    pl: "Rezerwacje",
    tr: "Rezervasyonlar",
    hi: "बुकिंग",
    nl: "Boekingen",
    vi: "Đặt chỗ",
    ru: "Бронирования",
    sv: "Bokningar",
    no: "Bestillinger",
    fi: "Varaukset",
    da: "Bookinger",
    cs: "Rezervace",
    hu: "Foglalások",
    ro: "Rezervări",
    bg: "Резервации",
    el: "Κρατήσεις",
    th: "การจอง",
  },
  myJobs: {
    en: "My Jobs",
    uk: "Завдання",
    de: "Meine Aufträge",
    es: "Mis trabajos",
    fr: "Mes travaux",
    it: "I miei lavori",
    "zh-CN": "我的工作",
    "zh-TW": "我的工作",
    ja: "マイジョブ",
    ko: "내 작업",
    "pt-BR": "Meus trabalhos",
    ar: "وظائفي",
    pl: "Moje prace",
    tr: "İşlerim",
    hi: "मेरे काम",
    nl: "Mijn opdrachten",
    vi: "Công việc của tôi",
    ru: "Мои работы",
    sv: "Mina jobb",
    no: "Mine jobber",
    fi: "Työni",
    da: "Mine jobs",
    cs: "Moje práce",
    hu: "Munkáim",
    ro: "Lucrările mele",
    bg: "Моите задачи",
    el: "Οι εργασίες μου",
    th: "งานของฉัน",
  },
  findJobs: {
    en: "Find Jobs",
    uk: "Пошук",
    de: "Jobs finden",
    es: "Buscar trabajos",
    fr: "Trouver des emplois",
    it: "Trova lavori",
    "zh-CN": "寻找工作",
    "zh-TW": "尋找工作",
    ja: "仕事を探す",
    ko: "일자리 찾기",
    "pt-BR": "Encontrar trabalhos",
    ar: "البحث عن وظائف",
    pl: "Znajdź pracę",
    tr: "İş Bul",
    hi: "नौकरियां खोजें",
    nl: "Opdrachten zoeken",
    vi: "Tìm việc làm",
    ru: "Найти работу",
    sv: "Hitta jobb",
    no: "Finn jobber",
    fi: "Etsi töitä",
    da: "Find jobs",
    cs: "Najít práci",
    hu: "Munkák keresése",
    ro: "Găsește lucrări",
    bg: "Намери работа",
    el: "Βρείτε εργασίες",
    th: "หางาน",
  },
  map: {
    en: "Map",
    uk: "Карта",
    de: "Karte",
    es: "Mapa",
    fr: "Carte",
    it: "Mappa",
    "zh-CN": "地图",
    "zh-TW": "地圖",
    ja: "地図",
    ko: "지도",
    "pt-BR": "Mapa",
    ar: "خريطة",
    pl: "Mapa",
    tr: "Harita",
    hi: "नक्शा",
    nl: "Kaart",
    vi: "Bản đồ",
    ru: "Карта",
    sv: "Karta",
    no: "Kart",
    fi: "Kartta",
    da: "Kort",
    cs: "Mapa",
    hu: "Térkép",
    ro: "Hartă",
    bg: "Карта",
    el: "Χάρτης",
    th: "แผนที่",
  },
  calendar: {
    en: "Calendar",
    uk: "Календар",
    de: "Kalender",
    es: "Calendario",
    fr: "Calendrier",
    it: "Calendario",
    "zh-CN": "日历",
    "zh-TW": "日曆",
    ja: "カレンダー",
    ko: "캘린더",
    "pt-BR": "Calendário",
    ar: "التقويم",
    pl: "Kalendarz",
    tr: "Takvim",
    hi: "कैलेंडर",
    nl: "Kalender",
    vi: "Lịch",
    ru: "Календарь",
    sv: "Kalender",
    no: "Kalender",
    fi: "Kalenteri",
    da: "Kalender",
    cs: "Kalendář",
    hu: "Naptár",
    ro: "Calendar",
    bg: "Календар",
    el: "Ημερολόγιο",
    th: "ปฏิทิน",
  },
  welcome: {
    en: "Welcome to EZ Clear",
    uk: "Ласкаво просимо до EZ Clear",
    de: "Willkommen bei EZ Clear",
    es: "Bienvenido a EZ Clear",
    fr: "Bienvenue sur EZ Clear",
    it: "Benvenuto su EZ Clear",
    "zh-CN": "欢迎使用 EZ Clear",
    "zh-TW": "歡迎使用 EZ Clear",
    ja: "EZ Clear へようこそ",
    ko: "EZ Clear에 오신 것을 환영합니다",
    "pt-BR": "Bem-vindo ao EZ Clear",
    ar: "مرحباً بك في EZ Clear",
    pl: "Witaj w EZ Clear",
    tr: "EZ Clear'a Hoş Geldiniz",
    hi: "EZ Clear में आपका स्वागत है",
    nl: "Welkom bij EZ Clear",
    vi: "Chào mừng đến với EZ Clear",
    ru: "Добро пожаловать в EZ Clear",
    sv: "Välkommen till EZ Clear",
    no: "Velkommen til EZ Clear",
    fi: "Tervetuloa EZ Cleariin",
    da: "Velkommen til EZ Clear",
    cs: "Vítejte v EZ Clear",
    hu: "Üdvözöljük az EZ Clear-ben",
    ro: "Bine ați venit la EZ Clear",
    bg: "Добре дошли в EZ Clear",
    el: "Καλώς ήλθατε στο EZ Clear",
    th: "ยินดีต้อนรับสู่ EZ Clear",
  },
  selectAppUse: {
    en: "Select how you want to use the app",
    uk: "Виберіть, як використовувати додаток",
    de: "Wählen Sie aus, wie Sie die App verwenden möchten",
    es: "Selecciona cómo quieres usar la aplicación",
    fr: "Sélectionnez comment vous souhaitez utiliser l'application",
    it: "Seleziona come vuoi utilizzare l'app",
    "zh-CN": "选择您希望如何使用应用",
    "zh-TW": "選擇您希望如何使用應用程式",
    ja: "アプリの使用方法を選択してください",
    ko: "앱을 어떻게 사용하고 싶은지 선택하세요",
    "pt-BR": "Selecione como deseja usar o aplicativo",
    ar: "حدد كيف تريد استخدام التطبيق",
    pl: "Wybierz, jak chcesz korzystać z aplikacji",
    tr: "Uygulamayı nasıl kullanmak istediğinizi seçin",
    hi: "चुनें कि आप ऐप का उपयोग कैसे करना चाहते हैं",
    nl: "Selecteer hoe je de app wilt gebruiken",
    vi: "Chọn cách bạn muốn sử dụng ứng dụng",
    ru: "Выберите, как вы хотите использовать приложение",
    sv: "Välj hur du vill använda appen",
    no: "Velg hvordan du vil bruke appen",
    fi: "Valitse, miten haluat käyttää sovellusta",
    da: "Vælg hvordan du vil bruge appen",
    cs: "Vyberte, jak chcete aplikaci používat",
    hu: "Válassza ki, hogyan szeretné használni az alkalmazást",
    ro: "Selectați cum doriți să utilizați aplicația",
    bg: "Изберете как искате да използвате приложението",
    el: "Επιλέξτε πώς θέλετε να χρησιμοποιήσετε την εφαρμογή",
    th: "เลือกวิธีที่คุณต้องการใช้แอป",
  },
  wantToWork: {
    en: "I want to work",
    uk: "Я хочу працювати",
    de: "Ich möchte arbeiten",
    es: "Quiero trabajar",
    fr: "Je veux travailler",
    it: "Voglio lavorare",
    "zh-CN": "我想工作",
    "zh-TW": "我想工作",
    ja: "働きたい",
    ko: "일하고 싶습니다",
    "pt-BR": "Quero trabalhar",
    ar: "أريد العمل",
    pl: "Chcę pracować",
    tr: "Çalışmak istiyorum",
    hi: "मैं काम करना चाहता हूँ",
    nl: "Ik wil werken",
    vi: "Tôi muốn làm việc",
    ru: "Я хочу работать",
    sv: "Jag vill arbeta",
    no: "Jeg vil jobbe",
    fi: "Haluan työskennellä",
    da: "Jeg vil arbejde",
    cs: "Chci pracovat",
    hu: "Dolgozni szeretnék",
    ro: "Vreau să lucrez",
    bg: "Искам да работя",
    el: "Θέλω να εργαστώ",
    th: "ฉันต้องการทำงาน",
  },
  wantToHire: {
    en: "I want to hire",
    uk: "Я хочу найняти",
    de: "Ich möchte einstellen",
    es: "Quiero contratar",
    fr: "Je veux embaucher",
    it: "Voglio assumere",
    "zh-CN": "我想雇用",
    "zh-TW": "我想雇用",
    ja: "雇いたい",
    ko: "고용하고 싶습니다",
    "pt-BR": "Quero contratar",
    ar: "أريد التوظيف",
    pl: "Chcę zatrudnić",
    tr: "İşe almak istiyorum",
    hi: "मैं किराए पर लेना चाहता हूँ",
    nl: "Ik wil inhuren",
    vi: "Tôi muốn thuê",
    ru: "Я хочу нанять",
    sv: "Jag vill anställa",
    no: "Jeg vil ansette",
    fi: "Haluan palkata",
    da: "Jeg vil ansætte",
    cs: "Chci najmout",
    hu: "Alkalmazni szeretnék",
    ro: "Vreau să angajez",
    bg: "Искам да наема",
    el: "Θέλω να προσλάβω",
    th: "ฉันต้องการจ้าง",
  },
  continue: {
    en: "Continue",
    uk: "Продовжити",
    de: "Fortfahren",
    es: "Continuar",
    fr: "Continuer",
    it: "Continua",
    "zh-CN": "继续",
    "zh-TW": "繼續",
    ja: "続ける",
    ko: "계속",
    "pt-BR": "Continuar",
    ar: "استمرار",
    pl: "Kontynuuj",
    tr: "Devam Et",
    hi: "जारी रखें",
    nl: "Doorgaan",
    vi: "Tiếp tục",
    ru: "Продолжить",
    sv: "Fortsätt",
    no: "Fortsett",
    fi: "Jatka",
    da: "Fortsæt",
    cs: "Pokračovat",
    hu: "Folytatás",
    ro: "Continuă",
    bg: "Продължи",
    el: "Συνέχεια",
    th: "ดำเนินการต่อ",
  },
  forgotPassword: {
    en: "Forgot Password",
    uk: "Забули пароль",
    de: "Passwort vergessen",
    es: "Olvidé mi contraseña",
    fr: "Mot de passe oublié",
    it: "Password dimenticata",
    "zh-CN": "忘记密码",
    "zh-TW": "忘記密碼",
    ja: "パスワードを忘れた",
    ko: "비밀번호 찾기",
    "pt-BR": "Esqueceu a senha",
    ar: "نسيت كلمة المرور",
    pl: "Zapomniałem hasła",
    tr: "Şifremi Unuttum",
    hi: "पासवर्ड भूल गए",
    nl: "Wachtwoord vergeten",
    vi: "Quên mật khẩu",
    ru: "Забыли пароль",
    sv: "Glömt lösenord",
    no: "Glemt passord",
    fi: "Unohtunut salasana",
    da: "Glemt adgangskode",
    cs: "Zapomenuté heslo",
    hu: "Elfelejtett jelszó",
    ro: "Am uitat parola",
    bg: "Забравена парола",
    el: "Ξέχασα τον κωδικό",
    th: "ลืมรหัสผ่าน",
  },
  languageChanged: {
    en: "Language changed",
    uk: "Мову змінено",
    de: "Sprache geändert",
    es: "Idioma cambiado",
    fr: "Langue modifiée",
    it: "Lingua cambiata",
    "zh-CN": "语言已更改",
    "zh-TW": "語言已更改",
    ja: "言語が変更されました",
    ko: "언어가 변경되었습니다",
    "pt-BR": "Idioma alterado",
    ar: "تم تغيير اللغة",
    pl: "Zmieniono język",
    tr: "Dil değiştirildi",
    hi: "भाषा बदल दी गई है",
    nl: "Taal gewijzigd",
    vi: "Đã thay đổi ngôn ngữ",
    ru: "Язык изменен",
    sv: "Språk ändrat",
    no: "Språk endret",
    fi: "Kieli vaihdettu",
    da: "Sprog ændret",
    cs: "Jazyk změněn",
    hu: "Nyelv megváltoztatva",
    ro: "Limbă schimbată",
    bg: "Езикът е променен",
    el: "Η γλώσσα άλλαξε",
    th: "เปลี่ยนภาษาแล้ว",
  },
  services: {
    en: "Services",
    uk: "Послуги",
    ru: "Услуги",
    de: "Dienstleistungen",
    es: "Servicios",
    fr: "Services",
    it: "Servizi",
    "zh-CN": "服务",
    "zh-TW": "服務",
    ja: "サービス",
    ko: "서비스",
    "pt-BR": "Serviços",
    ar: "الخدمات",
    pl: "Usługi",
    tr: "Hizmetler",
    hi: "सेवाएं",
    nl: "Diensten",
    vi: "Dịch vụ",
    ru: "Услуги",
    sv: "Tjänster",
    no: "Tjenester",
    fi: "Palvelut",
    da: "Tjenester",
    cs: "Služby",
    hu: "Szolgáltatások",
    ro: "Servicii",
    bg: "Услуги",
    el: "Υπηρεσίες",
    th: "บริการ",
  },
  renovation: {
    en: "Renovation",
    uk: "Ремонт",
    ru: "Ремонт",
    de: "Renovierung",
    es: "Renovación",
    fr: "Rénovation",
    it: "Ristrutturazione",
    "zh-CN": "装修",
    "zh-TW": "裝修",
    ja: "リフォーム",
    ko: "리모델링",
    "pt-BR": "Reforma",
    ar: "تجديد",
    pl: "Remont",
    tr: "Yenileme",
    hi: "नवीनीकरण",
    nl: "Renovatie",
    vi: "Cải tạo",
    sv: "Renovering",
    no: "Renovering",
    fi: "Remontti",
    da: "Renovering",
    cs: "Rekonstrukce",
    hu: "Felújítás",
    ro: "Renovare",
    bg: "Ремонт",
    el: "Ανακαίνιση",
    th: "การปรับปรุง",
  },
  snowRemoval: {
    en: "Snow Removal",
    uk: "Прибирання снігу",
    ru: "Уборка снега",
    de: "Schneeräumung",
    es: "Remoción de nieve",
    fr: "Déneigement",
    it: "Rimozione neve",
    "zh-CN": "除雪",
    "zh-TW": "除雪",
    ja: "除雪",
    ko: "제설",
    "pt-BR": "Remoção de neve",
    ar: "إزالة الثلوج",
    pl: "Odśnieżanie",
    tr: "Kar Temizleme",
    hi: "बर्फ हटाना",
    nl: "Sneeuwruimen",
    vi: "Dọn tuyết",
    sv: "Snöröjning",
    no: "Snørydding",
    fi: "Lumenpoisto",
    da: "Snerydning",
    cs: "Odklízení sněhu",
    hu: "Hóeltakarítás",
    ro: "Îndepărtare zăpadă",
    bg: "Почистване на сняг",
    el: "Αφαίρεση χιονιού",
    th: "การกำจัดหิมะ",
  },
  outdoor: {
    en: "Outdoor",
    uk: "Надвір",
    ru: "На улице",
    de: "Außenbereich",
    es: "Exterior",
    fr: "Extérieur",
    it: "Esterno",
    "zh-CN": "户外",
    "zh-TW": "戶外",
    ja: "屋外",
    ko: "야외",
    "pt-BR": "Exterior",
    ar: "خارجي",
    pl: "Na zewnątrz",
    tr: "Dış mekan",
    hi: "बाहरी",
    nl: "Buiten",
    vi: "Ngoài trời",
    sv: "Utomhus",
    no: "Utendørs",
    fi: "Ulkotila",
    da: "Udendørs",
    cs: "Venkovní",
    hu: "Kültéri",
    ro: "Exterior",
    bg: "На открито",
    el: "Εξωτερικού χώρου",
    th: "กลางแจ้ง",
  },
  availableJobs: {
    en: "Available Jobs",
    uk: "Доступні роботи",
    ru: "Доступные работы",
    de: "Verfügbare Jobs",
    es: "Trabajos disponibles",
    fr: "Emplois disponibles",
    it: "Lavori disponibili",
    "zh-CN": "可用工作",
    "zh-TW": "可用工作",
    ja: "利用可能な仕事",
    ko: "이용 가능한 작업",
    "pt-BR": "Trabalhos disponíveis",
    ar: "الوظائف المتاحة",
    pl: "Dostępne prace",
    tr: "Mevcut İşler",
    hi: "उपलब्ध कार्य",
    nl: "Beschikbare opdrachten",
    vi: "Công việc có sẵn",
    sv: "Tillgängliga jobb",
    no: "Tilgjengelige jobber",
    fi: "Saatavilla olevat työt",
    da: "Tilgængelige jobs",
    cs: "Dostupné práce",
    hu: "Elérhető munkák",
    ro: "Lucrări disponibile",
    bg: "Налични задачи",
    el: "Διαθέσιμες εργασίες",
    th: "งานที่มีอยู่",
  },
  details: {
    en: "Details",
    uk: "Деталі",
    ru: "Детали",
    de: "Details",
    es: "Detalles",
    fr: "Détails",
    it: "Dettagli",
    "zh-CN": "详情",
    "zh-TW": "詳情",
    ja: "詳細",
    ko: "상세 정보",
    "pt-BR": "Detalhes",
    ar: "التفاصيل",
    pl: "Szczegóły",
    tr: "Detaylar",
    hi: "विवरण",
    nl: "Details",
    vi: "Chi tiết",
    sv: "Detaljer",
    no: "Detaljer",
    fi: "Tiedot",
    da: "Detaljer",
    cs: "Podrobnosti",
    hu: "Részletek",
    ro: "Detalii",
    bg: "Детайли",
    el: "Λεπτομέρειες",
    th: "รายละเอียด",
  },
  apply: {
    en: "Apply",
    uk: "Подати",
    ru: "Подать",
    de: "Bewerben",
    es: "Aplicar",
    fr: "Postuler",
    it: "Candidati",
    "zh-CN": "申请",
    "zh-TW": "申請",
    ja: "応募",
    ko: "지원",
    "pt-BR": "Candidatar-se",
    ar: "تقديم",
    pl: "Aplikuj",
    tr: "Başvur",
    hi: "आवेदन करें",
    nl: "Solliciteer",
    vi: "Ứng tuyển",
    sv: "Ansök",
    no: "Søk",
    fi: "Hae",
    da: "Ansøg",
    cs: "Přihlásit se",
    hu: "Jelentkezés",
    ro: "Aplică",
    bg: "Кандидатствай",
    el: "Υποβολή",
    th: "สมัคร",
  },
  viewAll: {
    en: "View All",
    uk: "Всі",
    ru: "Все",
    de: "Alle anzeigen",
    es: "Ver todo",
    fr: "Voir tout",
    it: "Vedi tutti",
    "zh-CN": "查看全部",
    "zh-TW": "查看全部",
    ja: "すべて表示",
    ko: "모두 보기",
    "pt-BR": "Ver tudo",
    ar: "عرض الكل",
    pl: "Zobacz wszystkie",
    tr: "Tümünü Gör",
    hi: "सभी देखें",
    nl: "Alles bekijken",
    vi: "Xem tất cả",
    ru: "Все",
    sv: "Visa alla",
    no: "Se alle",
    fi: "Näytä kaikki",
    da: "Se alle",
    cs: "Zobrazit vše",
    hu: "Összes megtekintése",
    ro: "Vezi toate",
    bg: "Виж всички",
    el: "Προβολή όλων",
    th: "ดูทั้งหมด",
  },
  post: {
    en: "Post",
    uk: "Додати",
    ru: "Добавить",
    de: "Posten",
    es: "Publicar",
    fr: "Publier",
    it: "Pubblica",
    "zh-CN": "发布",
    "zh-TW": "發布",
    ja: "投稿",
    ko: "게시",
    "pt-BR": "Publicar",
    ar: "نشر",
    pl: "Dodaj",
    tr: "Yayınla",
    hi: "पोस्ट",
    nl: "Plaatsen",
    vi: "Đăng",
    sv: "Publicera",
    no: "Publiser",
    fi: "Julkaise",
    da: "Opslå",
    cs: "Přidat",
    hu: "Közzététel",
    ro: "Postează",
    bg: "Публикувай",
    el: "Δημοσίευση",
    th: "โพสต์",
  },
  cancel: {
    en: "Cancel",
    uk: "Скасувати",
    ru: "Отмена",
    de: "Abbrechen",
    es: "Cancelar",
    fr: "Annuler",
    it: "Annulla",
    "zh-CN": "取消",
    "zh-TW": "取消",
    ja: "キャンセル",
    ko: "취소",
    "pt-BR": "Cancelar",
    ar: "إلغاء",
    pl: "Anuluj",
    tr: "İptal",
    hi: "रद्द करें",
    nl: "Annuleren",
    vi: "Hủy",
    ru: "Отмена",
    sv: "Avbryt",
    no: "Avbryt",
    fi: "Peruuta",
    da: "Annuller",
    cs: "Zrušit",
    hu: "Mégse",
    ro: "Anulează",
    bg: "Отказ",
    el: "Ακύρωση",
    th: "ยกเลิก",
  },
}

// Define context type
interface LanguageContextType {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
  availableLanguages: { code: Language; name: string }[]
}

// Create context
const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Create provider component
export function LanguageProvider({ children }: { children: ReactNode }) {
  // Initialize language from localStorage if available
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const savedLanguage = localStorage.getItem("language") as Language
      return savedLanguage || "en"
    }
    return "en"
  })

  // Create a list of available languages
  const availableLanguages = [
    { code: "en" as Language, name: "English" },
    { code: "uk" as Language, name: "Українська" },
    { code: "ru" as Language, name: "Русский" },
    { code: "de" as Language, name: "Deutsch" },
    { code: "es" as Language, name: "Español" },
    { code: "fr" as Language, name: "Français" },
    { code: "it" as Language, name: "Italiano" },
    { code: "zh-CN" as Language, name: "简体中文" },
    { code: "zh-TW" as Language, name: "繁體中文" },
    { code: "ja" as Language, name: "日本語" },
    { code: "ko" as Language, name: "한국어" },
    { code: "pt-BR" as Language, name: "Português (Brasil)" },
    { code: "ar" as Language, name: "العربية" },
    { code: "pl" as Language, name: "Polski" },
    { code: "tr" as Language, name: "Türkçe" },
    { code: "hi" as Language, name: "हिन्दी" },
    { code: "nl" as Language, name: "Nederlands" },
    { code: "vi" as Language, name: "Tiếng Việt" },
    { code: "sv" as Language, name: "Svenska" },
    { code: "no" as Language, name: "Norsk" },
    { code: "fi" as Language, name: "Suomi" },
    { code: "da" as Language, name: "Dansk" },
    { code: "cs" as Language, name: "Čeština" },
    { code: "hu" as Language, name: "Magyar" },
    { code: "ro" as Language, name: "Română" },
    { code: "bg" as Language, name: "Български" },
    { code: "el" as Language, name: "Ελληνικά" },
    { code: "th" as Language, name: "ไทย" },
  ]

  // Update localStorage when language changes
  useEffect(() => {
    if (typeof window !== "undefined") {
      localStorage.setItem("language", language)

      // Force update any components that might not be directly using the context
      document.documentElement.setAttribute("lang", language)
      document.documentElement.setAttribute("dir", language === "ar" ? "rtl" : "ltr")

      // Dispatch a custom event to notify other components about the language change
      const event = new CustomEvent("languageChanged", { detail: { language } })
      document.dispatchEvent(event)

      // Show toast notification
      toast({
        title: "Language changed",
        description: availableLanguages.find((lang) => lang.code === language)?.name || language,
      })

      // Save to user profile if logged in
      try {
        fetch("/api/user/language", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            language,
          }),
        }).catch((err) => console.error("Failed to save language preference to profile:", err))
      } catch (error) {
        console.error("Error saving language preference:", error)
      }
    }
  }, [language])

  // Function to set language
  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage)
  }

  // Translation function
  const t = (key: string): string => {
    if (!key) return ""

    // Set fallback language
    const fallbackLanguage: Language = "en"
    let translatedText: string | undefined

    // Handle nested keys (e.g., "section.key")
    if (key.includes(".")) {
      const [section, subKey] = key.split(".")
      translatedText = translations[section]?.[subKey]?.[language]

      // First fallback: Try English if current language translation is missing
      if (!translatedText && language !== fallbackLanguage) {
        translatedText = translations[section]?.[subKey]?.[fallbackLanguage]

        // Log missing translation if in development
        if (process.env.NODE_ENV === "development" && translatedText) {
          logMissingTranslation(key, language)
        }
      }

      // Return the translation or the key as last resort
      return translatedText || key
    }

    // Handle direct keys with the same fallback logic
    translatedText = translations[key]?.[language]

    // First fallback: Try English if current language translation is missing
    if (!translatedText && language !== fallbackLanguage) {
      translatedText = translations[key]?.[fallbackLanguage]

      // Log missing translation if in development
      if (process.env.NODE_ENV === "development" && translatedText) {
        logMissingTranslation(key, language)
      }
    }

    // Return the translation or the key as last resort
    return translatedText || key
  }

  // Add a function to log missing translations
  const logMissingTranslation = (key: string, missingLanguage: Language) => {
    console.warn(`[Translation] Missing translation for key "${key}" in language "${missingLanguage}"`)

    // You could also collect these in an array or send to a server endpoint
    if (typeof window !== "undefined" && window.localStorage) {
      try {
        // Get existing missing translations log or initialize a new one
        const missingTranslationsLog = JSON.parse(localStorage.getItem("missingTranslations") || "{}")

        // Structure: { "language": { "key1": true, "key2": true, ... } }
        if (!missingTranslationsLog[missingLanguage]) {
          missingTranslationsLog[missingLanguage] = {}
        }

        missingTranslationsLog[missingLanguage][key] = true

        // Save back to localStorage
        localStorage.setItem("missingTranslations", JSON.stringify(missingTranslationsLog))
      } catch (e) {
        console.error("Failed to log missing translation to localStorage", e)
      }
    }
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, availableLanguages }}>
      {children}
    </LanguageContext.Provider>
  )
}

// Create hook for using the language context
export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
